name: Teste do build - main

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-aplication:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Buildar a aplicação
        run: |
          dotnet build
          echo "Build concluído com sucesso! ✅"
